version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - .:/app
    env_file:
      - .env

  db-init:
    build: .
    volumes:
      - ./data:/app/data
      - .:/app
    env_file:
      - .env
    command: python scripts/import_csv.py
    profiles:
      - init

  db-admin:
    image: coleifer/sqlite-web
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    command: sqlite_web -H 0.0.0.0 -x /data/pokemon_rater.db
    profiles:
      - admin