version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - .:/app
    env_file:
      - .env

  db-init:
    build: .
    volumes:
      - ./data:/app/data
      - .:/app
    env_file:
      - .env
    command: python scripts/import_csv.py
    profiles:
      - init