services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - .:/app
    env_file:
      - .env
    networks:
      - app_net

  db-init:
    build: .
    volumes:
      - ./data:/app/data
      - .:/app
    env_file:
      - .env
    command: python scripts/import_csv.py
    profiles:
      - init
    networks:
      - app_net

  db-admin:
    image: coleifer/sqlite-web
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    command: sqlite_web --host 0.0.0.0 /data/pokemon_rater.db
    profiles:
      - admin
    networks:
      - app_net

networks:
  app_net:
    name: pokemonrater_net
    driver: bridge